#!/usr/bin/env python3.5
import argparse
from bacch import run

# Main Process
if __name__ == '__main__':

    parser = argparse.ArgumentParser()

    # Options
    parser.add_argument('-k', '--working-dir', default = '.')
    parser.add_argument('-v', '--verbose', action = 'store_true')
    parser.add_argument('-b', '--build')
    parser.add_argument('-o', '--output', default='build')

    args = parser.parse_args()
    run(args)
