#!/usr/bin/env python3.5
""" This script provides the initial entry for Bacch.

Bacch is a document and static site generator designed
to provide various self-publishing tools for fiction
and technical writers.
"""

# Module Imports
import argparse
from bacch import run

########################
# Main Process
parser = argparse.ArgumentParser()

# Options
parser.add_argument('-k', '--working-dir', default='.')
parser.add_argument('-v', '--verbose', action='store_true')
parser.add_argument('-l', '--logfile', default='bacch.log')
parser.add_argument('--master', default='master.xml')
parser.add_argument('--debug', action='store_true')
parser.add_argument('--extension', default='xml')
parser.add_argument('-b', '--build')

# Commands
parser.add_argument('-S', '--sync', action='store_true')
parser.add_argument('-f', '--force', action='store_true')

args = parser.parse_args()
run(args)
